language: node_js
node_js:
  - "node"
script:
  -
deploy:
  provider: firebase
  token:
    secure: "EOiByPxNjaICAR3i3l82VuFpXoTyXnC6eD0sh+/+5n5eiGj1YH3hNiq0UUxAt+KJGaDIvA4nKWVHG+z3i33ytwaJBPKLrRzSgMIVJY6z3Z84yleYWu5UhwmQ2x2xXzWEfZpWqgfDG313/sxjOI6JzRRnaKefBf0HU3fu/FUhkpeOpuWiZGHmV6698VXAQm7r//l3A5AmwjJH9ok9ep++1v5IcvudHcVwDijoi+kWrYFUNMpcm2xcVHBqsN3qRQ6YiFuiMxnqS6Chz0VC6bKxiuPkzhTCrBapzexDbrubB1qLS7D606y+grWW4/0SAzHD1T56mupyjSLpJQZix/SvmJwfk9CMKOQU0/3wMPltomUftvfN3L5HLvTtxDWe+WS+y62YAJu7GOSwY7NBERJ/nDOUse9Rcz7GlvaeJuKQbjCtHO9J98FPqNB+ywKGpWeK+42BdB2q6lSfG/yB2oqx+KBjJUiKQBQ0l6QAzmF3WH9k/wuFrtDvh3XmjljBC1WIk11XsJJCWP7BkfCCGc6rw50oQM1kwTFUSiNa6VfG7YKXv4qjVaSazXMsACzu/QQCvY6diMLNuG9h/ylavaOoGiasT/dQpwAI6Yzns9T1qG+YxH9dQHvcwUPtCw2crMZbTP4J3/eAPyBPXLSOMPrN9u7BBySjyMjYqGL9TonfVMk="
  skip_cleanup: true
  message: "deploy via Travis CI"